### ISSUE TITLE
Affordability

### ISSUE THREAD

**Issue by jarmitage** [Algorave/guidelines#6]
https://github.com/Algorave/guidelines/blob/9006a3b38af68b0bba4df201ac768b014fd782c3/README_en.md?plain=1#L20

Class is mentioned here, but perhaps this particular aspect could be further highlighted:

Algorave event makers should prioritise affordability so that attendees are not priced out

Where affordability is limited, pay what you can options, that include channels for private arrangement of such, should be clearly published on promotional materials

**Comment by ojack** [comment]
this is great <3

**Comment by madamsapple** [comment]
Hi there! I wanted to contribute to this issue and include the affordability part for audiences. Could you please let me know if I can still rewrite the document? This is what I had in mind:

_To ensure inclusivity in audiences as well, algorave events should prioritise affordability and provide multiple pricing options. If affordability is limited, performances can introduce pay-what-you-can options. Transparency should always be maintained by clearly stating these details on promotional materials or online ticketing systems._

Let me know if it needs further editing. Thanks and look forward to your response!

**Comment by yaxu** [comment]
Thanks for picking this up @madamsapple ! I think the overall vibe for this document is a set of guidelines rather than rules, so I'd soften and simplify it a bit, e.g:

To further support inclusivity in audiences, algorave events should consider affordability, for example by providing transparent 'pay-what-you-can-afford' pricing options.

I've not seen events that don't publicise ticket prices transparently, so think it's not worth including that in detail, but very happy to be corrected if that is a problem in some places. Did you have particular experience of that @jarmitage ?

**Comment by jarmitage** [comment]
I didn't experience that exact situation. 

I think the softer language suggestion is good. Would be nice to merge this in!

Thanks @madamsapple for reviving it
